### ISSUE TITLE
Consider ExtensionContext.storageUri for private data

### ISSUE THREAD

**Issue by bclement-ocp** [OCamlPro/superbol-studio-oss#107]
While running inside VScode, we could use [ExtensionContext.storageUri](https://code.visualstudio.com/api/references/vscode-api#ExtensionContext.storageUri) to store data instead of having extra `_superbol` directories everywhere.

**Comment by bclement-ocp** [comment]
If I open a Cobol file w/o `superbol.toml`, I get a `_superbol` directory there. `superbol.toml` should not be required to use Superbol (in fact, the extension mostly works without when auto-detection doesn't get confused).

**Comment by GitMensch** [comment]
Totally agreed. In any case I suggest:
A setting to specify where this folder is, defaulting to NULL.

NULL then means: check every directory from the files part "up" for a folder .suberbol (. instead of _), if it exists, take this one. If there isn't one use the `ExtensionContext.storageUri`. With a web extension only the latter one can be used, if I remember correctly.

**Comment by nberth** [comment]
I agree with the idea to have this URI as a fallback if no `superbol.toml` is found. Note, though, that at the moment this `_superbol` directory is only used to store a cache. Hence, the caveat will probably be that, if that VSCode-provided storage space is used, then any other `superbol-free` command that is launched from the terminal will not be able to re-use this cache; but we may live with that.

Investigating the specification of the "standard" LSP protocol quickly, it does not seem to cover the exchange of such information from `ExtensionContext` (unless I missed some bits). One simple way to pass this URI may therefore be as an argument to `superbol-free lsp` (maybe as `--fallback-storage-uri`…). Whether this storage space would need to be shared among several projects still eludes me.

**Comment by nberth** [comment]
> `superbol.toml` should not be required to use Superbol

This is true when one only has the LSP in mind. But SuperBOL does not reduce to the LSP only. It already features several built-in commands that help dealing with projects that make use of  GnuCOBOL (like the switches implemented by Fabrice, or snapshots). Those may also need access to some of the COBOL-related configuration, and it is easier to design them independently from the LSP (even if only at development stage, until appropriate portions of client extensions are designed).

**Comment by GitMensch** [comment]
friendly ping - I still see errors in the general extensions output pane:

> [error] Error: Exception caught while saving project caches: Unix.Unix_error(Unix.EACCES, "mkdir", "XYZ/_superbol")

**Comment by nberth** [comment]
TODO:
- [ ] Add a flag to enable using VSCode-provided storage on demand;
- [ ] Silence cache-related errors.
