### ISSUE TITLE
Add `check syntax` sub-command for `superbol-free`

### ISSUE THREAD

**Issue by nberth** [OCamlPro/superbol-studio-oss#142]

**Comment by GitMensch** [comment]
What would this be used for? Isn't the LSP running in watch mode while editing a file, or would this subcommand raise a message where the"normal" LSP ignores something or doesn't understand?

**Comment by nberth** [comment]
This command shall be a sub-command of the `superbol-free` CLI executable, that will allow us to better report missing support for compiler directives or COBOL constructs in the LSP's grammar.
