### ISSUE TITLE
Incorrect folding

### ISSUE THREAD

**Issue by engboris** [OCamlPro/superbol-studio-oss#150]
I tested all [worldcities](https://github.com/OCamlPro/gnucobol-contrib/blob/master/samples/worldcities/) files (which are written in free format) on Visual Studio Code Version 1.85.2. Here are several common errors related to folding:

1. `identification division` folds the whole source code except for `worldcities5` and `worldcities6` (but I assume it is because of syntax errors). In all cases, it goes far beyond the identification division;
2. for the `file section` in `data division`, the fold button appears at the wrong position, one line after (on the next `fd` sentence, typically);
3. same thing for `working-storage section`, the fold button appears at the next definition when there're at least two definitions but it does not appear at all for a single declaration;
4. in [worldcities0.cbl](https://github.com/OCamlPro/gnucobol-contrib/blob/master/samples/worldcities/worldcities0.cbl) L83-92:
```cobol
working-storage section.

01  command-file-name pic x(128) value 'worldcities0.sh'.
01  techtonics.
    03  pic x(128) value 'export FILES=$HOME/worldcityfiles'.
    03  pic x(128) value
        'cobc worldcities0.cbl -x -W -fdebugging-line'.
    03  pic x(128) value './worldcities0 $FILES/CA.txt'.
    03  pic x(128) value 'rm worldcities0'.
    03  pic x(128) value 'end'.
```
it looks like the continuation line `'cobc worldcities0.cbl -x -W -fdebugging-line'.` (L89) is mistakenly taken for a sub-level variable, making a fold button appear at the `03  pic x(128) value` just before (L88). This happens for continuations lines in general;

5. it may be related but in [worldcities5.cbl](https://github.com/OCamlPro/gnucobol-contrib/blob/master/samples/worldcities/worldcities5.cbl) L161:
```cobol
           03  run-line.
               05  display-count pic z,zzz,zzzb.
               05  display-elapsed-seconds
                   redefines display-count pic zz,zz9.99b.
               05  display-message pic x(62).
```
there is a fold button on `run-line`, as expected and on `display-elapsed-seconds` as explained in the last point but also on `display-count ` which folds `redefines display-count pic zz,zz9.99b.`.

## Remark

In case of "conflicts" between fold positions, there is a sudden increase of CPU usage. For instance, in the following code:
```cobol
working-storage section.

01  command-file-name pic x(128) value 'worldcities0.sh'.
01  techtonics.
    03  pic x(128) value 'export FILES=$HOME/worldcityfiles'.
    03  pic x(128) value
        'cobc worldcities0.cbl -x -W -fdebugging-line'.
    03  pic x(128) value './worldcities0 $FILES/CA.txt'.
    03  pic x(128) value 'rm worldcities0'.
    03  pic x(128) value 'end'.
```

The fold button for `working-storage section.` (mistakenly) appears at `01  command-file-name pic x(128) value 'worldcities0.sh'.` (L85) but if we define sub-levels for `command-file-name`:
```cobol
working-storage section.

01  command-file-name pic x(128) value 'worldcities0.sh'.
    03  ...
    03  ...
    03  ...
01  techtonics.
    03  pic x(128) value 'export FILES=$HOME/worldcityfiles'.
    03  pic x(128) value
        'cobc worldcities0.cbl -x -W -fdebugging-line'.
    03  pic x(128) value './worldcities0 $FILES/CA.txt'.
    03  pic x(128) value 'rm worldcities0'.
    03  pic x(128) value 'end'.
```

Then a fold button should have also appeared for it, being in conflict with the former one. But such conflicts should not happen anyway and I assume it should be solved by correcting folding.

**Comment by GitMensch** [comment]
When working on folding, you likely want to at least have a look at how https://github.com/OCamlPro/superbol-studio-oss/blob/master/test/testsuite/microfocus/www.csis.ul.ie/SubProg/DateValid/ValiDate.cbl is handled (MF format), as well as how code with `EXEC SQL` look like - for example as contained in https://github.com/opensourcecobol/Open-COBOL-ESQL/blob/develop/tests/sqlca.src/insert-select-update-delete.at.

And, which is possibly "master class" check "old standard COBOL85", like in https://github.com/opensourcecobol/opensourcecobol4j/blob/ea00ca59d1c28037a75c25b5da67c4223d8876be/tests/cobol85/NC/NC107A.CBL which has _actual_ COBOL continuation lines as well as "noise" in col1-6,73-80

**Comment by nberth** [comment]
#163 should fix the issue with incorrect folding ranges.

I have not witnessed any new issue with CPU usage, though.
