### ISSUE TITLE
Fix left-alignment of IBM test files

### ISSUE THREAD

**Issue by nberth** [OCamlPro/superbol-studio-oss#151]
*cf* https://github.com/OCamlPro/superbol-studio-oss/commit/e98687164af376259ebcb04cbe73b301a1446802#commitcomment-137790264

**Comment by nberth** [comment]
@GitMensch At last here's the fix. The files actually seem to use IBM's EXTENDED format, with lines of 252 bytes (https://www.ibm.com/docs/en/cobol-linux-x86/1.2?topic=options-srcformat). Strangely enough that format is not available in GnuCOBOL… is it an omission when we added `-fformat`? or a misreading on my side?

**Comment by GitMensch** [comment]
That's not really an omission as that should be used as this format is only available in [IBM COBOL for Linux x86](https://www.ibm.com/docs/en/cobol-linux-x86/1.2?topic=options-srcformat) while on the Enterprise COBOL, there's [only the COBOL85 version](https://www.ibm.com/docs/en/cobol-zos/6.4?topic=reference-cobol-language-structure).

And where it _is_ used the variable format should be enough to cover that.
