### ISSUE TITLE
handling of conditional compilation (and `EXEC SQL`)

### ISSUE THREAD

**Issue by GitMensch** [OCamlPro/superbol-studio-oss#161]
This sample program was shared on the IBM extension:

```cobol
       IDENTIFICATION DIVISION.
       PROGRAM-ID. TSTSQLCA.
       DATA DIVISION.
       WORKING-STORAGE SECTION.
       01  HOWMUCH PIC S9(9) COMP-5.
       >>define isDB2 as b'1'
       >>if isDB2
           exec sql include sqlca end-exec.
       >>end-if
       PROCEDURE DIVISION.
       MAIN.
           exec sql
             select count(*) into :HOWMUCH
             from SYSIBM.SYSDUMM1
           end-exec
           if SQLCODE not = 0 and SQLCODE not = +100
             display "Oups !"
           end-if
           .
       BYE.
           goback.
```

I'm "quite sure" that the LSP also has a problem here (it should error if the `>>define` line is removed, and pass otherwise (and of course, know that `HOMMUCH` is used within the SQL statement).

**Comment by nberth** [comment]
Indeed.
Conditional compilation shall be handled before the first release.
Handling of `EXEC`s might be very partial at first, but is planned as well.

**Comment by GitMensch** [comment]
Partial handling (just "skipping" it, possibly recognize `:hostname` references) for `EXEC SQL` is fine; doing lsp on the sql part itself would be interesting but can definitely come late.

I'd also say that conditional compilation may not be needed in the first version - the ibm extension only got it quite recently, bitlang.cobol didn't have that for years (it _may_ has now, no idea).

When adding conditional compilation - please handle both ISO (as above) as well as Micro Focus - same `WORKING-STORAGE` there:

```cobol
       78 isDB2 value 1,
       $IF isDB2
           exec sql include sqlca end-exec.
       $END
```

**Comment by GitMensch** [comment]
Just a ping as this would definitely be needed to not break editing of production code.

**Comment by GitMensch** [comment]
As this was closed - do we have initial support for conditional compilation in now, too?

If not and this is planned for later then this should be split out to us own issue.

**Comment by nberth** [comment]
> As this was closed - do we have initial support for conditional compilation in now, too?

Support for conditional compilation is currently under active development. Some of that is already in, but a PR will complete that very soon (likely tomorrow, next week at the latest).
