### ISSUE TITLE
hard dependency on tamasfe.even-better-toml

### ISSUE THREAD

**Issue by GitMensch** [OCamlPro/superbol-studio-oss#192]
As far as I see that's for better supporting the superbol configuration - Could this extension be "suggested" only instead of the hard dependency? vscode declined to install the superbol extension because the toml one was not installed.

**Comment by nberth** [comment]
I tried to find a way to only suggest it. Maybe I did not search hard enough…
One way could be to create an "extension pack", but I'm not sure if that requires a separate VSIX or not.

**Comment by GitMensch** [comment]
Yes the "common" way for that are extension packs which is nearly only a package.json with a relevant README and metadata that includes dependencies only, packaged as vsix.
