### ISSUE TITLE
bug: words are "recognized" with the default "C style"

### ISSUE THREAD

**Issue by GitMensch** [OCamlPro/superbol-studio-oss#197]
While the COBOL word recognition was added to the debugging part (`registerEvaluatableExpressionProvider`) it is missing in the plain editor. I don't know if this is about the tm syntax or an lsp part, but if I put the cursor into `SOME-VAR`, then the complete word should be highlighted, not only the part before/after the hyphen.

**Comment by nberth** [comment]
I think this may boil down to customizing word separators in the text editor. Apparently this can be done via the extension (*cf* https://github.com/Microsoft/vscode/issues/33701).
