### ISSUE TITLE
Implicit build task should be the debug build task

### ISSUE THREAD

**Issue by ddeclerck** [OCamlPro/superbol-studio-oss#219]
So that launching debugging when there is no `tasks.json` file works.

I.e the debug build task in `tasks.json` should contain:
```
			"group": {
				"kind": "build",
				"isDefault": true
			}
```

That should probably be handled in `attributes_spec` (`superbol_tasks.ml`).

**Comment by nberth** [comment]
`isDefault` does not seem to be modifiable via the API (*cf* https://vscode-api.js.org/classes/vscode.TaskGroup.html#isDefault). There's probably a better way to have the extension work properly without the `tasks.json`.
