### ISSUE TITLE
Wrong size in `RENAMES` range

### ISSUE THREAD

**Issue by nberth** [OCamlPro/superbol-studio-oss#294]
This a bug, it should say `ALPHANUMERIC(3)`.
It's a bit to byte conversion error originating here:
https://github.com/OCamlPro/superbol-studio-oss/blob/eba5c0c142735132b5e32385f8afba851e47539c/src/lsp/cobol_typeck/typeck_data_items.ml#L696-L701

_Originally posted by @NeoKaios in https://github.com/OCamlPro/superbol-studio-oss/pull/293#discussion_r1617374535_

**Comment by NeoKaios** [comment]
Here are some code snippets to test this on:
```cobol
01 STRUCT.
    02 VAR1 PIC X.
    02 VAR2 PIC X.
    66 RENAMED RENAMES VAR1 THRU VAR2.
```
`RENAMED` should probably be ALPHANUMERIC(2)

```cobol
01 STRUCT.
    02 VAR1 PIC X.
    02 VAR2 PIC 1 USAGE BIT.
    66 RENAMED RENAMES VAR1 THRU VAR2.
```
This may be forbidden by the rules of renames, not sure.
