### ISSUE TITLE
Document completion features in `README.md`

### ISSUE THREAD

**Issue by nberth** [OCamlPro/superbol-studio-oss#309]
Followup of #304 (and coming)

**Comment by GitMensch** [comment]
The feature is nice and the documentation important.
May I suggest that this issue gets someone assigned (or is this a "someone creates a PR" only workflow)?

Can you please push a new version to OpenVSX once this documentation is added?

**Comment by GitMensch** [comment]
also missing: #317 - I'm really looking forward to the next version being available via OpenVSX
