### ISSUE TITLE
superbol-vscode-debug: bug: `type: "gdb"` overrides system debugger

### ISSUE THREAD

**Issue by GitMensch** [OCamlPro/superbol-studio-oss#324]
The problem is that with the current type, I cannot debug native C programs any more, because "gdb" conflicts with the native.debug extension.

I suggest to use `cob-gdb` or something else instead.

**Comment by nberth** [comment]
Note: with changes in https://github.com/OCamlPro/superbol-vscode-debug/pull/8, selecting `Start  Debugging` from the menu with no `launch.json` does nothing (previously that started a debug session). I'm not sure what is causing that.
