### ISSUE TITLE
Check and fix auto-indent on free format

### ISSUE THREAD

**Issue by lefessan** [OCamlPro/superbol-studio-oss#43]
Check that auto-indent is correctly implemented on most COBOL files in free format.

**Comment by bclement-ocp** [comment]
I am not sure what "most COBOL files in free format" means. I can confirm that in the current `master` version:

 - The indentation looks mostly reasonable on the files I have tested (a subset of the MF testsuite in the repo — adapting the comments to make it "free form" and not X/Open)
 - The indentation seems to be properly limited to the selected range (when only a range, not the whole file, is indented)

The indenter could probably be better in a lot of ways (see discussion with @nberth regarding using token projections — but also the indenter currently makes a single huge "document change" request, which is not good and I will try to fix), but it looks useable.

**Comment by nberth** [comment]
Thanks @bclement-ocp , I think we can close this issue with your comments ;-)
