### ISSUE TITLE
Move LSP configuration to a per-project file

### ISSUE THREAD

**Issue by lefessan** [OCamlPro/superbol-studio-oss#47]
We should create a library `superbol_project` for this per-project file that is common to LSP but also other possible tools (linter, builder, etc.).

**Comment by GitMensch** [comment]
Not sure how the configuration part is done but for the LSP I'd suggest (from low to high priority):

* in-built-defaults
* installation defaults [ideal, but optional]
* system configuration [ideal, but optional]
* per project configuration
* command line switches if applicable

Then, depending on how the LSP is used/started (one new started for each project/workspace/user in vscode?) pass a additional set that may override those as command (in json/xml/whatever format), that comes from vscode settings; which automatically will use

* plugin setting defaults
* user configuration
* workspace configuration
