### ISSUE TITLE
Colorization of Copybooks

### ISSUE THREAD

**Issue by lefessan** [OCamlPro/superbol-studio-oss#48]
Currently, Copybooks are not colorized at all.

**Comment by nberth** [comment]
Partially dealt with by #200

**Comment by nberth** [comment]
Although quite possible with the current LSP server implementation, colorization of copybooks using semantic tokens is a luxury that we dont really need at the moment.
So I think we can consider that #200 closes this issue.

**Comment by GitMensch** [comment]
Agreed. I'd suggest that there could be a milestone "past 1.0" or similar, and this one may include an issue about using the LSP (semantic tokens).
