### ISSUE TITLE
Improve completion

### ISSUE THREAD

**Issue by lefessan** [OCamlPro/superbol-studio-oss#49]
Currently, the LSP does not help for completion of words:
* First version: add keyword context-free completion
* Second version:  add context sensitive completion (i.e. depending on the location)

**Comment by GitMensch** [comment]
not sure of your time schedule for beta, but I'd suggest to opt for early release (= no, or context-free completion)

**Comment by nberth** [comment]
Partly done in #304 , improved in #312.

**Comment by nberth** [comment]
Closing: #315 brings context-sensitive completion.
