### ISSUE TITLE
Documentation on Vscode marketplace

### ISSUE THREAD

**Issue by lefessan** [OCamlPro/superbol-studio-oss#51]

**Comment by GitMensch** [comment]
All marketplaces, as well as other clients, render README (see #50) and CHANGELOG as well as the metadata entries from package.json.
I therefore would suggest to close this as duplicate (possibly after CHANGES and CHANGELOG file are merged) and the entries in package.json are rechecked.

**Comment by GitMensch** [comment]
Even as a reminder I'd suggest to move that to the alpha release milestone.

**Comment by nberth** [comment]
Closing as completed via the `README.md`
