### ISSUE TITLE
Generalize `goto-definitions` and `find-references`

### ISSUE THREAD

**Issue by nberth** [OCamlPro/superbol-studio-oss#53]
Extend the current support for definitions in `WORKING-STORAGE` to other sections of the `DATA DIVISION`.

Achieving this requires:
- [x] Some preliminary refactoring and simplification of the parse-tree definitions (to be moved into a new `cobol_ptree` library);
- [x] Rework of `cobol_data` and `cobol_typeck`;
- [x] Maybe some minor adaptations in `cobol_lsp`.

**Comment by nberth** [comment]
@GitMensch While advancing on this, I'm ending up needing a clarification regarding level 01 constant entries (could apply to level-78 ones as well). ISO/IEC COBOL 2014 states "[The constant name] may be used anywhere that a format specifies a literal of the class and category of [the constant name]," which in itself is not precise-enough to decide whether to perform substitutions before or after parsing. In GnuCOBOL, this is done before, in the scanner, which appears a simple-enough solution at first glance. However, substitutions are effectively performed in any syntactic context, which implies that the following example program raises a syntax error:
```cobol
       IDENTIFICATION DIVISION.
       PROGRAM-ID. constant-01-test.
       DATA DIVISION.
       WORKING-STORAGE SECTION.
       01 XX.
         02 AA PIC XX VALUE "AA".
         02 BB PIC XX VALUE "BB".
       01 XX CONSTANT "BB".
       PROCEDURE DIVISION.
           DISPLAY BB IN XX.
```
```text
constant-01-tests.cob:9: error: syntax error, unexpected Literal, expecting Identifier
    7 |        01 XX CONSTANT "BB".
    8 |        PROCEDURE DIVISION.
    9 >            DISPLAY BB IN XX.
   10 | <EOF>
```
However, the format for qualified names does not accept any literal in the position of the qualifiers (`XX` in the example). So I'm wondering, is this actually a behavior that is observed on actual mainframes? I'd be ok to make the LSP match GnuCOBOL's way for doing ths, but I'd rather double-check before.

**Comment by GitMensch** [comment]
> the format for qualified names does not accept any literal in the position of the qualifiers (`XX` in the example)

... which is the reason for the error message. A qualification needs an identifier.
You _may_ be able to improve that by postponing, in this case you can raise a better error message like

> syntax error, unexpected constant name 'XX`, expecting qualification

But let's check what the standard says. We have 8.4.6 "scope of names" that specifies under "8.4.6.2.2    Scope of condition-names, constant-names, ..."

> A constant-name [...] described with a `GLOBAL` clause is a global name. All data-names and screen-names subordinate to a global name are global names. A constant-name, data-name, [...} declared in a source element for an object definition, whether factory or instance, is a global name. [...]
>
>When a condition-name, constant-name, data-name, [...] is not a global name, it is a local name.
>
>The requirements governing the uniqueness of the names allocated by a single source element to be condition-names, constant-names, data-names, [...] are explained elsewhere in these specifications. (See 8.3.2.2, User-defined words.)

Which then specifies:

> Within a source element, a given user-defined word may be used as only one type of user-defined word 
with the following [...exception:] the same name may be used as any of the following types of user-defined words:
* constant-name
* data-name
* property-name
* record-key-name
* record-name

... but as 13.10.4.1 specifies
>  [...] the effect of specifying constant-name-1 in other than this entry is as if literal-1 [... is] written where constant-name-1 is written

I don't think the rules are clear. I'll ask the working group by mail.
Side note: Wikipedia says that
> Association Française de Normalisation [AFNOR ... is a] [member body](https://en.wikipedia.org/wiki/Category:ISO_member_bodies) for France at the [International Organization for Standardization](https://en.wikipedia.org/wiki/International_Organization_for_Standardization) (ISO).

It is not clear to me which of those sub-organizations, if any, takes care of programming languages. I suggest you check with them as they don't have someone in the working group and _may_ also not commented on the last versions.
You may be able to volunteer for that and by this also get access to both the documents of the working group (which were sadly moved to a non-public area which can only be accessed by ISO accounts (also given out to international member bodies) and to the working group itself.

**Comment by GitMensch** [comment]
One thing that is fine per standard is the duplicate definition, I'm quite sure that this won't work with GnuCOBOL (patches welcome):

```
       01 XX CONSTANT "BB".
       01 XX CONSTANT "BB".
```

should raise zero messages

should raise an error:

```
       01 XX CONSTANT "BB".
       01 XX CONSTANT "Bb".
```

like 

> constant-name cannot be redefined with a different value ... first defined here ...

Same should apply for the extension level 78 constants.

**Comment by nberth** [comment]
Thanks a lot for investigating. (Indeed, I'm not sure we have a direct way to contact the working group).

> One thing that is fine per standard is the duplicate definition, I'm quite sure that this won't work with GnuCOBOL (patches welcome):
> 
> ```
>        01 XX CONSTANT "BB".
>        01 XX CONSTANT "BB".
> ```
> 
> should raise zero messages

Hum… current situation regarding those does not look good:
```text
constant-01-tests.cob:8: error: a constant may not be used here - 'XX'                                                                                      
    6 |          02 BB PIC XX VALUE "BB".
    7 |        01 XX CONSTANT "BB".
    8 >        01 XX CONSTANT "BB".
    9 |        PROCEDURE DIVISION.
   10 |            DISPLAY BB IN XX.

cobc: tree.c:2139: invalid cast from 'internal error node' type CONSTANT to type REFERENCE

cobc: aborting compile of constant-01-tests.cob at line 8 (PROGRAM-ID: constant-01-test)

cobc: Please report this!
```
during lookup of constant `XX` (?).

To me the possibility for duplicate entries is an indication that they should be regarded as plain language constructs, and dealing with them too early in the scanner may not be appropriate.

**Comment by GitMensch** [comment]
> Indeed, I'm not sure we have a direct way to contact the working group

In general your national body should be able to either point out in the standard where this is defined, or ask the CDG (current name since sometime 2022: COBOL Development Group, previously COBOL Working Group) itself.
It would be useful in any case to check with them about whom of the national member body of France to point questions regarding ISO/IEC 1989:2023 to. After all they had a vote in the review phase in 2002, 2010-2014  (that was a longer review with multiple iterations, some people reviewed as NO) and 2022!


I should be able to at least fix the abort easily and do agree that having this as a language construct and returned as either normal identifier or as constant to the parser would be useful. But obviously this needs several adjustments, starting with the parser, so that's something to consider for trunk / 4.x.
