### ISSUE TITLE
Planning: when (if at all) should the LSP at least parse NIST85 without errors?

### ISSUE THREAD

**Issue by GitMensch** [OCamlPro/superbol-studio-oss#54]
NIST85 has a lot of obsolete stuff in, most important is the line continuation including word continuation.

Then it has things that some preparsers stumble over (but that is also commonly used "somehow" in production code): fixed format with "comment" text in line 1-6, 73+ and minor ones like comment paragraphs (`AUTHOR` and friends).

It also has a lot of special PICTURE clauses and strange formatted code.

As I don't know what the state is: Is the LSP already able to parser all of NIST85 without errors?

... and a special thing: can it handle the programs that GnuCOBOL compiles and executes in its testsuite?
For the later one may use autofonce and set `COBC` to a shell that first sends the LSP to those files (expecting no output) and afterwards `cobc`. ... and of course something similar may be done with the NIST85 autofonce'd version (or again by exporting `COBC` to a shell that executes both).

**Comment by nberth** [comment]
@GitMensch I somehow forgot to deal with this issue before. As you may be able to observe in the new screenshots, yes the extension can deal with NIST85 already. And it can actually deal with *all* of it (even the obsolete stuff).

**Comment by GitMensch** [comment]
> As you may be able to observe in the new screenshots, yes the extension can deal with NIST85 already. And it can actually deal with all of it (even the obsolete stuff).

That will be seen when the diagnostics are all enabled again, no?

**Comment by nberth** [comment]
> That will be seen when the diagnostics are all enabled again, no?

Actually, I forgot to mention the README is a ahead of its time: the diagnostics have not been filtered out yet. We might even never filter them out for that particular dialect. The fact that we don't see any problem on the screenshots means the extension parses those files properly.

**Comment by GitMensch** [comment]
> We might even never filter them out for that particular dialect. 

Sounds good.
The next thing is to put this to a bigger production code base. I opt to do that and give qualified feedback once you publish an alpha version. For planning: is there any schedule for its availability on Open-VSX or GH releases?
