### ISSUE TITLE
FR: distribute the language-server along with the .vsix

### ISSUE THREAD

**Issue by GitMensch** [OCamlPro/superbol-studio-oss#76]
> A slightly longer plan might be to ship the binary within the `vsix` extension file.

_Originally posted by @nberth in https://github.com/OCamlPro/superbol-studio-oss/issues/75#issuecomment-1781089922_

This issue is about doing so, using platform-specific extensions.

More details are found at https://code.visualstudio.com/api/working-with-extensions/publishing-extension#platformspecific-extensions and of course - for the client side - https://github.com/microsoft/vscode-vsce.

There would be one version for each "target" you want plus one extra without a target (which would need an external install and possibly configuration to reach it as it is now).

**Comment by bclement-ocp** [comment]
Do we need platform-specific extensions if we ship a version of the language server compiled to JavaScript?

**Comment by GitMensch** [comment]
No. That won't be necessary. But I don't know if/how that affects the performance.

Compiled to javascript may also be useful for vscode for web (without a VM).

**Comment by nberth** [comment]
Closing this as it has been completed by #124 .

Web-specific version will be discussed in a dedicated issue.
