### ISSUE TITLE
SourceFormat as an enum

### ISSUE THREAD

**Issue by Stevendeo** [OCamlPro/superbol-studio-oss#77]
this and the entries below should use an enum type, possibly with an additional string option

_Originally posted by @GitMensch in https://github.com/OCamlPro/superbol-studio-oss/pull/72#discussion_r1373213892_

**Comment by nberth** [comment]
> What should be the cases in the enum?

Let's say that `Cobol_config.DIALECT.all_canonical_names` might do. I'm about to update this list, but we can assume the name will stay.
