### ISSUE TITLE
provide outline view

### ISSUE THREAD

**Issue by GitMensch** [OCamlPro/superbol-studio-oss#82]
so far that is empty "no symbols found", but the LSP surely has information for that

**Comment by nberth** [comment]
Yes the LSP has all the information for this already, and as far as I can identify the implementation of the basic feature could be quite straightforward. I'll set this for β though, so we concentrate on completing what's "almost" working already.

**Comment by GitMensch** [comment]
With the parser handling the definitions and providing a "go to definition" now, the data is __verified__ to be available in the LSP.
I'm looking forward to see this feature being available and in README.md for the ß release!

Note: if I remember correctly the breadcrumb navigation is again another api (using the same lsp data), but also be quite useful.
![nav](https://github.com/OCamlPro/superbol-studio-oss/assets/6699539/26450286-7c5b-4593-92d2-b4ba8835268c)
That may be implemented together or separately.

**Comment by GitMensch** [comment]
Looks like possibly the [`registerDocumentSymbolProvider` part](https://code.visualstudio.com/api/language-extensions/programmatic-language-features#show-all-symbol-definitions-within-a-document) for "common" symbols and the [`registerWorkspaceSymbolProvider`](https://code.visualstudio.com/api/language-extensions/programmatic-language-features#show-all-symbol-definitions-in-folder) for global entry points (=`procedure divisions` and `ENTRY` in outermost programs) as well as `EXTERNAL` items may be useful here; also the [`registerReferenceProvider`](https://code.visualstudio.com/api/language-extensions/programmatic-language-features#find-all-references-to-a-symbol) seems useful to provide that directly (instead of the indirect query).
